update hero
storj-archived/storj.io pull request #216
Opened 2019-07-09 17:05 UTC by VinozzZ

<img width="1501" alt="Screen Shot 2019-07-09 at 1 05 06 PM" src="https://user-images.githubusercontent.com/22300958/60908576-36ab8200-a24a-11e9-915f-3afc04f42361.png">
based on https://www.figma.com/file/0saZ6iBgSsn8BQJUP8k5x1Pu/Storj.io-(Vanguard)?node-id=79%3A1222

2019-07-09 20:09 UTC, fuskovic commented
`Node Operator Waitlist >` needs to stack starting on `sm` media-query

<img width="486" alt="Screen Shot 2019-07-09 at 4 05 45 PM" src="https://user-images.githubusercontent.com/34631293/60919456-be51ba80-a263-11e9-858b-5421840950a4.png">

2019-07-09 20:10 UTC, fuskovic requested changes
Please make the changes related to responsiveness shown in the screenshot attached.

2019-07-09 20:28 UTC, VinozzZ commented
updated @fuskovic

2019-07-10 13:18 UTC, fuskovic approved these changes

2019-07-10 13:18 UTC, merged